### ISSUE TITLE
Feedback: Second Challenge Submission

### ISSUE THREAD

**Issue by anselb** [dmcg89/Core-Data-Structures#2]
- While most of your stack and queue classes were good, your ArrayQueue had a couple bugs. One of them has to do with the syntax difference of calling function vs getting a property, and the other has to do with a missing part of dequeue.
- I could not find any incorrect complexity annotations in your code, but I would recommend making it a little more clear what some of the variables are (e.g. n and b in hash table _resize), just to help quicken readability by a bit. 
- Your set tests are mostly fine the way they currently are, but you might consider varying the input to use strings in addition to integers.

**Comment by dmcg89** [comment]
Added more tests to use strings, fixed ArrayQueue.  Sorry I did not realize it was broken, I think I changed it 
 and broke it when I was helping someone figure it out
